### PR TITLE
[Bug] fix NPE in SQLCodeCheckInterceptor

### LINKED ISSUE #4061: [Bug] fix NPE in SQLCodeCheckInterceptor
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

execute the following command 
```
sh bin/linkis-cli -submitUser hadoop -engineType shell -codeType shell -code "whoami"
```

the error logs will shown
```
[INFO] User does not provide usr-configuration file. Will use default config
[INFO] user does not specify proxy-user, will use current submit-user "hadoop" by default.
[INFO] connecting to linkis gateway:http://127.0.0.1:9001
[ERROR] EXE0011,Error occured during execution: Failed to submit job
Caused by: org.apache.linkis.httpclient.exception.HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/entrance/submit request failed! ResponseBody is {"method":null,"status":1,"message":"operation failed(操作失败)s！the reason(原因)：NullPointerException: ","data":{"errorMsg":{"serviceKind":"linkis-cg-entrance","level":2,"port":9104,"errCode":0,"ip":"tv3-hadoop-06","desc":"operation failed(操作失败)s！the reason(原因)：NullPointerException: "}}}. errCode: 10905 ,desc: URL /api/rest_j/v1/entrance/submit request failed! ResponseBody is {"method":null,"status":1,"message":"operation failed(操作失败)s！the reason(原因)：NullPointerException: ","data":{"errorMsg":{"serviceKind":"linkis-cg-entrance","level":2,"port":9104,"errCode":0,"ip":"tv3-hadoop-06","desc":"operation failed(操作失败)s！the reason(原因)：NullPointerException: "}}}. ,ip: null ,port: 0 ,serviceKind: null ,ip: null ,port: 0 ,serviceKind: null
############Execute Error!!!########
```

### Expected behavior

we need consider whether ```enginer type``` is null

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by GuoPhilipse**
fix #4061

### CODE REVIEW

File: linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/SQLCodeCheckInterceptor.scala [hunk 1]
```diff
@@ -26,8 +26,15 @@ import org.apache.linkis.manager.label.utils.LabelUtil
 class SQLCodeCheckInterceptor extends EntranceInterceptor {
 
   override def apply(jobRequest: JobRequest, logAppender: java.lang.StringBuilder): JobRequest = {
-    val engineType = LabelUtil.getCodeType(jobRequest.getLabels)
-    val languageType = CodeAndRunTypeUtils.getLanguageTypeByCodeType(engineType.toLowerCase())
+    val engineType = {
+      val engineType = LabelUtil.getCodeType(jobRequest.getLabels)
```
Comment (guoshupei) [inline linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/SQLCodeCheckInterceptor.scala:30]: It is better to change engineType to codeType

Comment (GuoPhilipse) [reply linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/SQLCodeCheckInterceptor.scala]: > It is better to change engineType to codeType

Thanks @guoshupei  ,have updated variable name to avoid misunderstanding.

**Review by guoshupei — COMMENTED** [review]
LGTM

**Review by peacewong — APPROVED** [review]
LGTM.
