### PR TITLE
[fix #1761]command "ip addr" maybe return multiple ips

### LINKED ISSUE #1761: [Bug] config.sh get mutiple ip
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

When there are multiple network cards, there is a problem with the IP address it obtains.
 I suggest letting users choose one.
截图_选择区域_20220320113643

### Relevent platform

deepin  20.4

### Reproduction script

ip addr | awk '/^[0-9]+: / {}; /inet.*global/ {print gensub(/(.*)\/(.*)/, "\\1", "g", $2)}'

### Anything else

Linkis Component can not select "assembly-combined-package" in "Issue: Bug report" page

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by iture123**
### What is the purpose of the change
 #1761

### Brief change log
command "ip addr" maybe return multiple ips,fix the situation.

### Verifying this change
(Please pick either of the following options)  
This change is a trivial rework / code cleanup without any test coverage.  

### Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): no
- Anything that affects deployment: no
- The MGS(Microservice Governance Services), i.e., Spring Cloud Gateway, OpenFeign, Eureka.: no

### Documentation
- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by casionone** [comment]
The install scrptis `web/install.sh`
Some useless operations shell code should be removed
```
echo '安装visualis前端,用户自行编译linkis前端安装包，则安装时需要把visualis的前端安装包放置于此'$linkis_basepath/linkis/visualis'，用于自动化安装:'
cd $linkis_basepath/linkis/visualis;unzip -o build.zip  > /dev/null
```
This code is useless and can easily cause confusion，Please help to delete it

**Comment by iture123** [comment]
> The install scrptis `web/install.sh` Some useless operations shell code should be removed
> 
> ```
> echo '安装visualis前端,用户自行编译linkis前端安装包，则安装时需要把visualis的前端安装包放置于此'$linkis_basepath/linkis/visualis'，用于自动化安装:'
> cd $linkis_basepath/linkis/visualis;unzip -o build.zip  > /dev/null
> ```
> 
> This code is useless and can easily cause confusion，Please help to delete it

already deleted

File: web/config.sh [hunk 1]
```diff
@@ -14,11 +14,13 @@
...
-#linkis ip address
-linkis_ipaddr=$(ip addr | awk '/^[0-9]+: / {}; /inet.*global/ {print gensub(/(.*)\/(.*)/, "\\1", "g", $2)}')
+#URL of the backend service of linkis-mg-gateway
+linkis_url="http://127.0.0.1:9001"
+
+#linkis ip address，the http access address for linkis-web will be http://${linkis_ipaddr}:${linkis_port}
+linkis_ipaddr=127.0.0.1
+linkis_port=8088
+
+web/install.sh
```
Comment (casionone) [inline web/config.sh:26]: exce web/install.sh action in config scripts?it seems unreasonable
