### PR TITLE
Fix the issue that the keys of put and remove in Map used in CliHeartbeatMonitor are not the same

### LINKED ISSUE #2038: [Bug] [Entrance]The keys of put and remove in the Map used in CliHeartbeatMonitor are not the same
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

The keys of put and remove in the Map used in CliHeartbeatMonitor are not the same, which will lead to memory leaks
image

### Relevent platform

all

### Reproduction script

no

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by peacewong**
### What is the purpose of the change
closed #2038

### Brief change log
- Fix the issue that the keys of put and remove in Map used in CliHeartbeatMonitor are not the same

### CODE REVIEW

File: linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/cli/heartbeat/CliHeartbeatMonitor.scala [hunk 1]
```diff
@@ -38,38 +35,41 @@ class CliHeartbeatMonitor(handler: HeartbeatLossHandler) extends Logging {
...
-          error("registered duplicate job!! job-id: " + id)
-        } else {
-          infoMap.put(id, entranceJob)
-          info("registered cli job: " + id)
+    job match {
+      case entranceJob: EntranceJob =>
+        if (isCliJob(entranceJob)) {
+          val id = entranceJob.getJobRequest.getId.toString
+          if (infoMap.containsKey(id)) {
+            error("registered duplicate job!! job-id: " + id)
```
Comment (casionone) [inline linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/cli/heartbeat/CliHeartbeatMonitor.scala:51]: Using `job id:` in log printing is cleaner and should be consistent
日志打印中使用 job id 更清晰，而且应该保持统一

Comment (peacewong) [reply linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/cli/heartbeat/CliHeartbeatMonitor.scala:51]: > Using `job id:` in log printing is cleaner and should be consistent 日志打印中使用 job id 更清晰，而且应该保持统一

Thanks. I will fix it

**Review by casionone — APPROVED** [review]
